# -*- coding: utf-8 -*-
"""book_shop1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZDwaHC41gfjo-SEnDbZzx8d5FDi2lcGi
"""

def f(i):
  if(i[1]<100):
    return(i[0],i[1]+10)
  else:
    return i
orders = [ ["34587", "Learning Python, Mark Lutz", 4, 40.95], 
         ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
           ["77226", "Head First Python, Paul Barry", 3,32.95],
           ["88112", "Einführung in Python3, Bernd Klein",  3, 24.99]]
op=list(map(f,list(map(lambda x:(x[0],round(x[2]*x[3],2)),orders))))
print(op)