# -*- coding: utf-8 -*-
"""fizzbuzz

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZDwaHC41gfjo-SEnDbZzx8d5FDi2lcGi
"""

for i in range(1,51):
  if(i%3==0 and i%5==0):
    print('FizzBuzz')
  elif(i%3==0):
    print('Fizz')
  elif(i%5==0):
    print('Buzz')
  else:
    print(i)