# -*- coding: utf-8 -*-
"""frequency

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZDwaHC41gfjo-SEnDbZzx8d5FDi2lcGi
"""

d1={}
s=input("enter a string: ")
for i in s:
    d1.update({i:s.count(i)})
print(d1)