# -*- coding: utf-8 -*-
"""restart

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZDwaHC41gfjo-SEnDbZzx8d5FDi2lcGi
"""

s=input("enter a string: ")
count=s.count('r')
s=s[len(s)-1::-1].replace('r', '$',count-1)
print(s[len(s)::-1])