# -*- coding: utf-8 -*-
"""Shopping List App

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZDwaHC41gfjo-SEnDbZzx8d5FDi2lcGi

'''
# Shopping List App 
    We are going to make a "Shopping List" app. 
    Run the script to start using it.
    Put new things into the list one at a time
    Enter the word DONE - in all CAPS - to QUIT the program
    And once i quit, I want the app to show me everything thats on my list.
Hint 
    
    Step 1: Make a list to hold onto our items.
    Step 2: Print out instructions on how to use the app
    Step 3: Ask for new items
    Step 4: Add new items to our list
    Step 5: Be able to quit the app with DONE
    Step 6: print out the list
'''
"""

items=[]
print('Instructions on how to use the app :\n\tEnter all the new items.\n\tQuit the app with DONE.')
item=input()
while(item!='DONE'):
    items.append(item)
    item=input()
print('your final list of items is -->',items)