# -*- coding: utf-8 -*-
"""vowels

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18pAOvEClYRMAiSyu7_bexb_1FcAcTZRc
"""

l=['Alabama','California','Oklahoma','Florida']
ll=[]
vowels = ('a', 'e', 'i', 'o', 'u')
for i in l:
  new=i
  for j in range(0,len(i)):
    if (i[j].lower() in vowels):
      new = new.replace(i[j],"");
  ll.append(new);
print(ll)